### ISSUE TITLE
Segfault if user does not specify colorfile

### ISSUE THREAD

**Issue by shmalebx9** [kaugm/mmwm#6]
With the newest update, when the program is first compiled it causes a segmentation fault. The user needs to specify the colorfile or the default "/home/USER/.cache/wal/colors-mmwm.h" leads the dynamic colors function to nowhere and causes a segfault. The solution might be remedied by pulling the user's home directory through the $HOME environmental variable with the getenv function or by making the colors function check if the given path is valid before proceeding. I'd submit a pull request with a fix if I could but I'm a landscaper, not an engineer, and it seems like diagnosing the problem is as far as my minimal knowledge of C can get me.

**Comment by kaugm** [comment]
This is a good point, i just assumed that people would take a look at the config.h file before compiling the program.

I'll go with the latter suggestion: checking to see if a file exists at the specified path, otherwise mmwm should just simply use 2 preset colors for the border colors.

**Comment by kaugm** [comment]
@shmalebx9 so I just tried compiling again while leaving "USER" and did not get any errors when compiling (just the dynamic theming and the update_colors function didn't do anything. Could you attach a screenshot?

In mmwm.c I added a function to check if the mmwm-colors.h file exists before reading it. This wont fix the error you're getting (i dont think) but was probably necessary to add anyways

**Comment by shmalebx9** [comment]
Image of the segfault when running https://imgur.com/a/RM77O92
to be clear, I guessed that the segfault is caused by the colors file leading to nowhere since just changing that one line got rid of the segfault.

**Comment by shmalebx9** [comment]
pulling the newest changes fixes the problem completely. https://imgur.com/BrXvAzr
